config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'main#home'
  devise_for :users
  resources :rooms do
    resources :messages
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  #broadcasts_to :room
  broadcasts_to :room, inserts_by: :prepend
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  has_many :messages
  validates :name, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
# frozen_string_literal: true

class MainController < ApplicationController
  before_action :authenticate_user!

  def home; end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room

  def create
    @room.messages.create! params.required(:message)
                                 .permit(:body, :user_id, :author)
                                 .merge(user_id: current_user.id, author: current_user.username)
    redirect_to @room
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.create room_params
    redirect_to rooms_path
  end

  def show
    @room = Room.find(params[:id])
    @message = Message.new
    @messages = @room.messages.order(created_at: :desc)
    render 'show'
  end

  private

  def room_params
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/main_helper.rb
# frozen_string_literal: true

module MainHelper
end

app/helpers/messages_helper.rb
# frozen_string_literal: true

module MessagesHelper
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LiveChat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/home.html.erb
<h2>LiveChat</h2>

<% if current_user %>
  <h5>Welcome <%= current_user.username %>!</h5>
  <%= link_to "Public rooms", rooms_path %>
  <%= link_to "Private rooms" %>
  <p>
    <%= button_to "Log out", destroy_user_session_path, method: :delete %>
  </p>
<% else %>
  <%= link_to "Log in", new_user_session_path %> |
  <%= link_to "Sign up", new_user_registration_path %>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id(message) %>" class="message-container">
  <div class="message <%= 'current-user' if message.user_id == current_user.id %>">
    <small class="author"><b><%= (message.user_id == current_user.id) ? "" : message.author %></b></small>
    <small class="body"><%= message.body %></small><br>
    <small class="timestamp"><%= time_tag message.created_at, "data-local": "time-ago" %></small>
  </div>
</div>

app/views/messages/_new.html.erb
<%= form_with model: [ room, Message.new ] do |form| %>
  Type message:<br>
  <%= form.text_field :body %>
  <%= form.submit "Send message" %>
<% end %>

app/views/rooms/_headline.html.erb
<div>
  <h2>LiveChat<h2>
  <div>
    <h5>Welcome <%= current_user.username %>!</h5>
  </div>
</div> 

app/views/rooms/_messages.html.erb
<div class="room-container">
  <%= render room.messages %>
</div>
<%= render "messages/new", room: room %>

app/views/rooms/_room.html.erb
<div>
    <%= link_to room.name, room %>
</div>

app/views/rooms/index.html.erb
<div>
  <%= render 'headline' %>
</div>
<%= link_to "Create new room", new_room_path %>

<h5>Rooms</h5>
<%= turbo_stream_from "rooms" %>
<div id="rooms">
  <%= render @rooms %>
</div>

app/views/rooms/new.html.erb
<div>
  <%= render 'headline' %>
</div>

<%= form_with model: @room do |form| %>
  <div>
    <%= form.label :Room_name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/show.html.erb
<div>
  <%= render 'headline' %>
  <h5><%= @room.name %></h5>
</div>

<%= turbo_stream_from @room, :messages %>
<%= render "rooms/messages", room: @room %>

app/views/users/_user.html.erb
<div>
    <%#%>= link_to user.username, user %>
</div>